# Generated by Django 4.2.5 on 2023-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('seeking_gender', models.CharField(max_length=1)),
                ('self_introduction', models.CharField(max_length=200)),
                ('partner_expectation', models.CharField(max_length=200)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_bucket', models.PositiveIntegerField()),
            ],
        ),
    ]
